name: Keep
on:
  pull_request:
  schedule:
    - cron: "0 9 * * 3"  # every wednesday at 9am

jobs:
  keep-alive:
    name: Alive
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/keepalive-workflow@v1
        with:
          commit_message: "Ah ah ah, stayin' alive"
          committer_username: conda-forge-bot
          committer_email: "conda-forge-bot@users.noreply.github.com"
          time_elapsed: 50  # days